package models

import "time"

type ActionType string
type LocationType string
const (
	ActionEnter ActionType = "ENTRATA"
	ActionExit ActionType = "USCITA"
)
const (
	LocationOffice LocationType = "UFFICIO"
	LocationSmart LocationType = "SMART"
)

type Timbrature struct {
	ID        int `json:"id"`
	UserID    int `json:"user_id"`
	Timestamp time.Time `json:"timestamp"`
	ActionType ActionType `json:"action_type"`
	Location LocationType `json:"location"`
	Geolocation *string `json:"geolocation"`
}

// Request front-end -> back-end
// NO ID e Timestamp => id is generated by default from the database and timestamp is generated by the back-end
type CreateTimbratureRequest struct {
	UserID int `json:"user_id" binding:"required"`
	ActionType ActionType `json:"action_type" binding:"required"`
	Location LocationType `json:"location" binding:"required"`
	Geolocation *string `json:"geolocation"`
}
