package models

type UseRole struct {
	ID             int    `json:"id"`
	Name           string `json:"name"`
	HierarchyLevel int    `json:"hierarchy_level"`
}

// Request front-end -> back-end
// NO ID => generated by database by default
type CreateUserRoleRequest struct {
	Name           string `json:"name" binding:"required"`
	HierarchyLevel int    `json:"hierarchy_level" binding:"required"`
}