package models

type User struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	RoleID    *int   `json:"role_id"`
	ManagerID *int   `json:"manager_id"`
}

// Request front-end -> back-end
// NO ID => generated by database by default
type CreateUserRequest struct {
	Name      string `json:"name" binding:"required"`
	Email     string `json:"email" binding:"required"`
	RoleID    *int   `json:"role_id"`
	ManagerID *int   `json:"manager_id"`
}